# Generated by Django 4.2.7 on 2024-07-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
